# Generated by Django 3.2.9 on 2023-01-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='session_id',
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
