# Generated by Django 3.2.9 on 2023-01-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20230103_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинотеатры', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='filmgenre',
            options={'verbose_name': 'Жанры фильмов', 'verbose_name_plural': 'Жанры фильмов'},
        ),
        migrations.AlterModelOptions(
            name='filmproduction',
            options={'verbose_name': 'Страны-производители фильмов', 'verbose_name_plural': 'Страны-производители фильмов'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Залы', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='seatcategory',
            options={'verbose_name': 'Категории мест', 'verbose_name_plural': 'Категории мест'},
        ),
        migrations.AlterModelOptions(
            name='seatrow',
            options={'verbose_name': 'Места и ряды', 'verbose_name_plural': 'Места и ряды'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеансы', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='numbers',
            field=models.PositiveSmallIntegerField(max_length=12, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poster.filmgenre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poster.filmproduction', verbose_name='Страна-производитель'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=4, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='filmgenre',
            name='genre',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='filmproduction',
            name='production',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Страны-производители'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='category',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Категории мест'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poster.seatcategory', verbose_name='Категория мест'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='place',
            field=models.PositiveSmallIntegerField(max_length=4, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='row',
            field=models.PositiveSmallIntegerField(max_length=2, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='session',
            name='data_time',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
