# Generated by Django 3.2.9 on 2023-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20230103_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='photo/films/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='photo/news/%Y/%m'),
        ),
    ]
