# Generated by Django 3.2.9 on 2023-01-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_auto_20230104_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='data_time',
        ),
        migrations.AddField(
            model_name='session',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='numbers',
            field=models.PositiveSmallIntegerField(verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='row',
            field=models.PositiveSmallIntegerField(verbose_name='Ряд'),
        ),
    ]
