# Generated by Django 3.2.9 on 2023-01-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_auto_20230104_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Дата'),
        ),
    ]
