# Generated by Django 3.2.9 on 2023-01-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_alter_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
