# Generated by Django 3.2.9 on 2023-01-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_alter_session_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='data',
            new_name='data_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
    ]
