# Generated by Django 3.2.9 on 2023-01-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_auto_20230104_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poster.seatcategory', unique=True),
        ),
    ]
